name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deployment-${{ github.ref_name }}

jobs:
  terraform-apply:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Brioche
        uses: brioche-dev/setup-brioche@9b82d4ee697500f7d81f6397a943935ffa3d887b # v1.5.0

      - name: Install Terraform
        run: brioche install -r terraform

      - name: Cache terraform registry
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            .terraform
          key: terraform-apply-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-apply-

      - name: Apply the plan of Terraform
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
          TF_VAR_crates_io_api_token: ${{ secrets.TF_VAR_CRATES_IO_API_TOKEN }}
          BACKEND_ACCESS_KEY: ${{ secrets.BACKEND_ACCESS_KEY }}
          BACKEND_SECRET_KEY: ${{ secrets.BACKEND_SECRET_KEY }}
        run: |
          terraform init -backend-config=access_key="$BACKEND_ACCESS_KEY" -backend-config=secret_key="$BACKEND_SECRET_KEY"
          terraform apply -auto-approve
